# Generated by Django 4.2.1 on 2023-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
